name: backend-workflow
run-name: Started backend workflow
on: [pull_request, push, workflow_dispatch]
jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Setup maven
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-version: 17
      - name: Setup dependancies and testing
        run: mvn clean install
