name: Quality
run-name: Started quality workflow
on: 
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:
jobs:
  #testing:
    #name: Test workflow
    #uses: ./.github/workflows/test.yml
  front:
    name: Front Analyse
    runs-on: ubuntu-latest
    #needs: testing
    defaults:
      run:
        working-directory: ./front
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: download coverage report
        uses: actions/download-artifact@v4
        with:
          name: front-code-coverage-report
          path: ./front/coverage/bobapp/
          github-token: ${{ github.token }}
          #run-id: ${{ needs.testing.outputs.run-id }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: front/
            
  back:
    name: Back Analyse
    runs-on: ubuntu-latest
    #needs: testing
    defaults:
      run:
        working-directory: ./back
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup maven
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-version: |
            11
            17
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}
        run: mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=mathieu-hallez_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD_backend
